<?php
namespace Libs\Thrift\Packages\Scribe;

Use \Libs\Thrift\Packages\Fb303\FacebookServiceIf;

/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT_LIB'].'/packages/fb303/FacebookService.php';

interface ScribeIf extends FacebookServiceIf {
  public function Log($messages);
}
